apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      type: basic
  replicas: 3
  template:
    metadata:
      name: jupyter-app
      labels:
        type: basic
    spec:
      containers:
        - name: jupyter-minimal-notebook
          image: jupyter/minimal-notebook