apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  # See the lectures for a diagram of what this means. In sort it is forwarding
  # 80 on to the local port of 30008.
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
    # This tells it which services to match to. If more than one match they are
    # all exposed. It will connect at random to one of the nodes.
  selector:
    name: postgres-pod
    app: demo-voting-app